services:
  backend:
    build: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - ./back/data:/app/data
      - /app/node_modules

  frontend:
    build: ./front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules



  redis:
    image: redis:7-alpine

    

  worker:
    build: ./back
    command: npm run worker
    volumes:
      - ./back:/app
      - /app/node_modules
      - ./back/data:/app/data
    depends_on:
      - redis